### ISSUE TITLE
Calling println() in Locomotion snippets generates JVM error

### ISSUE THREAD

**Issue by chrisatkin** [chrisatkin/locomotion#2]

**Comment by chrisatkin** [comment]
Adding a println() to `ArrayAccessInstrumentation.load` produces:

`scope: GraalCompiler.BackEnd.LIRGen.InterceptException
Exception occurred in scope: GraalCompiler.BackEnd.LIRGen.InterceptException
Context obj com.oracle.graal.graph.GraalInternalError: java.lang.ClassCastException: uk.ac.ed.inf.icsa.locomotion.nodes.ArrayStoreNode cannot be cast to com.oracle.graal.nodes.spi.LIRLowerable
    at node: 45|ArrayStore
Context obj com.oracle.graal.hotspot.amd64.AMD64HotSpotLIRGenerator@6aa8ceb6
Context obj com.oracle.graal.lir.LIR@2530c12
Context obj StructuredGraph:2{HotSpotMethod<CodeSamples.vectorAddition()>}
Connected to the IGV on 127.0.0.1:4445
Context obj com.oracle.graal.hotspot.amd64.AMD64HotSpotRuntime@17d10166
Exception in thread "main" com.oracle.graal.graph.GraalInternalError: java.lang.ClassCastException: uk.ac.ed.inf.icsa.locomotion.nodes.ArrayStoreNode cannot be cast to com.oracle.graal.nodes.spi.LIRLowerable
    at node: 45|ArrayStore
    at com.oracle.graal.compiler.gen.LIRGenerator.doBlock(LIRGenerator.java:306)
    at com.oracle.graal.compiler.GraalCompiler$3.emitBlock(GraalCompiler.java:226)
    at com.oracle.graal.compiler.GraalCompiler$3.run(GraalCompiler.java:213)
    at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:179)
    at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:167)
    at com.oracle.graal.debug.Debug.scope(Debug.java:118)
    at com.oracle.graal.debug.Debug.scope(Debug.java:113)
    at com.oracle.graal.compiler.GraalCompiler.emitLIR(GraalCompiler.java:209)
    at com.oracle.graal.compiler.GraalCompiler$1$2.call(GraalCompiler.java:92)
    at com.oracle.graal.compiler.GraalCompiler$1$2.call(GraalCompiler.java:1)
    at com.oracle.graal.debug.internal.DebugScope.call(DebugScope.java:301)
    at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:182)
    at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:167)
    at com.oracle.graal.debug.Debug.scope(Debug.java:138)
    at com.oracle.graal.debug.Debug.scope(Debug.java:133)
    at com.oracle.graal.compiler.GraalCompiler$1.run(GraalCompiler.java:89)
    at com.oracle.graal.debug.internal.DebugScope.executeScope(DebugScope.java:179)
    at com.oracle.graal.debug.internal.DebugScope.scope(DebugScope.java:167)
    at com.oracle.graal.debug.Debug.scope(Debug.java:118)
    at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:79)
    at uk.ac.ed.inf.icsa.locomotion.Locomotion.compile(Locomotion.java:53)
    at uk.ac.ed.inf.icsa.locomotion.Application.run(Application.java:36)
    at uk.ac.ed.inf.icsa.locomotion.Application.main(Application.java:54)
Caused by: java.lang.ClassCastException: uk.ac.ed.inf.icsa.locomotion.nodes.ArrayStoreNode cannot be cast to com.oracle.graal.nodes.spi.LIRLowerable
    at com.oracle.graal.compiler.gen.LIRGenerator.emitNode(LIRGenerator.java:356)
    at com.oracle.graal.compiler.amd64.AMD64LIRGenerator.emitNode(AMD64LIRGenerator.java:100)
    at com.oracle.graal.compiler.gen.LIRGenerator.doRoot(LIRGenerator.java:351)
    at com.oracle.graal.compiler.gen.LIRGenerator.doBlock(LIRGenerator.java:302)
    ... 22 more`

**Comment by chrisatkin** [comment]
So far it appears that only `System.out.println()` generates this error. I can call `public void test(String s)` without the error.

**Comment by chrisatkin** [comment]
Snippets are no longer required.
